BOARD ::= ROW "x" COLUMN NEWLINE (REGION NEWLINE)+
REGION ::= STAR " " STAR " | " (COORDINATE)+
STAR ::= COORDINATE
COORDINATE ::= INT "," INT
ROW ::= INT
COLUMN ::= INT
INT ::= [0-10]
NEWLINE ::= "\n"